manifest:
  remotes:
    - name: lowprowkb
      url-base: https://github.com/LOWPROKB
  projects:
    - name: zmk
      remote: lowprokb
      revision: Board-Corne-ish-Zen-dedicated-work-queue
      #revision: corne-ish-zen-v2
      import: app/west.yml
  self:
    path: config
