name: Draw ZMK keymap
on:
  workflow_dispatch:
  push:
    branches:
      - pages
    paths:
      - "config/*.keymap"
      - "config/*.dtsi"
      - keymap_drawer.config.yaml
      - .github/workflows/draw-keymaps.yml

jobs:
  draw:
    permissions:
      contents: write
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    with:
      output_folder: "docs/img"
